language: node_js
sudo: false
git:
  depth: 3
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn run init
  - yarn run lint
  - yarn run test:cov
after_success:
  - yarn run coveralls
