language: node_js
git:
  depth: 3
cache:
  yarn: true
  directories:
    - "node_modules"
    - "coverage"
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
      script: yarn run lint      # Linting gotta pass
      script: yarn run test:cov  # Run the tests and generate coverage
      script: yarn run build     # Make sure building succeeds
after_success:
    - script: yarn run ci        # Submit coverage
